### ISSUE TITLE
Message : No such signal QComboBox

### ISSUE THREAD

**Issue by JasonChmn** [humanoid-path-planner/hpp-gepetto-viewer#41] opened 2020-05-07 12:02 UTC
I have these types of message when using hpp-gepetto-viewer :
```
Object::connect:  (receiver name: 'Visibility')
Object::connect: No such signal QComboBox::currentTextChanged(QString)
Object::connect:  (receiver name: 'WireframeMode')
Object::connect: No such signal QComboBox::currentTextChanged(QString)
Object::connect:  (receiver name: 'Highlight/State')
Object::connect: No such signal QComboBox::currentTextChanged(QString)
Object::connect:  (receiver name: 'LightingMode')
Object::connect: No such signal QComboBox::currentTextChanged(QString)
```
This is not blocking and gepetto viewer still works, but does someone know what could be the cause ? 
Thank you

**Comment by nim65s** [comment] 2020-05-07 12:11
I guess you have `robotpkg-py36-qt4-hpp-gepetto-viewer`, right ?

**Comment by JasonChmn** [comment] 2020-05-07 12:21
Yes

**Comment by jmirabel** [comment] 2020-05-07 12:33
I know what the cause is. The only disagreements it causes is that modifying an enum property from the corba interface will not modify the displayed value in the body tree.
This is working fine in Qt5 so I won't fix it.

**Closed** 2020-05-07 12:33 UTC
